baseURL: 'https://chrissyraffeiner.github.io/hugo-project/'
languageCode: 'en-us'
title: 'Leo-Database-Learner'
theme: myowntheme
copyright: Raffeiner Christine
author:
  name: Christine Raffeiner

menu:
  main:
    - name: Git-Repo
      url: https://github.com/htl-leonding-project/leo-database-learner
      weight: 1
    - name: Team
      url: /topics/team
      weight: 2
    - name: Overview
      url: /topics/
      weight: 1
    - name: System
      url: /topics/system
      weight: 2
    - name: Installation
      url: /topics/installation
      weight: 2